name: E-Nakes CI
env:
  ANDROID_SDK_PATH: ${{ github.workspace }}/android_sdk
run-name: ${{ github.actor }} is building E-Nakes üöÄ
on: [push]
jobs:
  e-nakes_ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Build Info
        run: | 
         echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
         echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
         echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Initialize CI
        run: |
         echo $ANDROID_SDK_PATH
         mkdir $ANDROID_SDK_PATH
         ls ${{ github.workspace }}
         echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
         echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: Download and install FVM
        run: |
          wget -q -O $ANDROID_SDK_PATH/fvm.tar.gz https://github.com/fluttertools/fvm/releases/download/2.4.1/fvm-2.4.1-linux-x64.tar.gz
          tar -xvzf $ANDROID_SDK_PATH/fvm.tar.gz -C $ANDROID_SDK_PATH
          cp $ANDROID_SDK_PATH/fvm/fvm /usr/local/bin/.
          chmod +x /usr/local/bin/fvm
          fvm --version
      - name: Download and install sdkmanager
        run: |
          wget -q -O $ANDROID_SDK_PATH/sdkmanager.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip $ANDROID_SDK_PATH/sdkmanager.zip -d $ANDROID_SDK_PATH
          mkdir $ANDROID_SDK_PATH/latest
          mv $ANDROID_SDK_PATH/cmdline-tools/* $ANDROID_SDK_PATH/latest/.
          $ANDROID_SDK_PATH/latest/bin/sdkmanager --list          
      - run: echo "üçè This job's status is ${{ job.status }}."
